# Generated by Django 4.2.22 on 2025-06-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0003_gradelevel_skillcategory_answerchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='answerchoice',
            old_name='questions',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='passage',
            old_name='body',
            new_name='text',
        ),
        migrations.AddField(
            model_name='passage',
            name='grade_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passages.gradelevel'),
        ),
        migrations.AddField(
            model_name='passage',
            name='skill_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passages.skillcategory'),
        ),
    ]
