# Generated by Django 4.2.22 on 2025-06-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0004_rename_questions_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
