# Generated by Django 4.2.22 on 2025-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0005_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
