# Generated by Django 4.2.23 on 2025-08-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0008_passage_uploader_uploadeddocument_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='skill_category',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
        migrations.DeleteModel(
            name='AnswerChoice',
        ),
        migrations.DeleteModel(
            name='Passage',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
