# Generated by Django 4.2.22 on 2026-07-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0009_remove_passage_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Time taken in seconds'),
        ),
    ]
