# Generated by Django 4.2.22 on 2026-07-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0010_quizresponse_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='program',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Reading'), ('shsat', 'SHSAT'), ('sat', 'SAT Reading & Writing')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passages.topic'),
        ),
    ]
