# Generated by Django 4.2.22 on 2026-07-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0011_profile_classroom'),
        ('passages', '0011_topic_uploadeddocument_difficulty_and_more'),
    ]

    operations = [
    ]
