# Generated by Django 4.2.22 on 2026-07-22 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passages', '0011_profile_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
