# Generated by Django 4.2.22 on 2026-07-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0012_classroom_join_code_classroom_students'),
        ('passages', '0012_merge_20260722_1452'),
    ]

    operations = [
    ]
